dist: trusty
sudo: false
language: go
go:
- '1.12'

env:
  global:
    - GO111MODULE=on
    # CODACY_TOKEN
    - secure: "RExXZyxgB1BqdJ7ZdYx5hCyvzPA3W5eR/iLRCWusoHgxEwKKTDO6qcRSsdMfczDqrBtNj4uoIFG+4ZvEb7QpFeCoDA9TX9QlPvcEuzlPSBoSH1qKjA3Ca0V85KfzmdjGTcG62bUJLzGskqGPcHDaJtU7Me/nGr7mtsh6nzDxGNoi/hUgT+gcUofr5wBel+Vo759vZIUnC7mjSboafu7f587ru1Bamc2xT1vUckW2hPfBKoseiq4aoYIeu04onm6Nip4UQzPRCxuQiev3d57csF+UmO66pxUadMAad1SxEiDS424XVWJa0vAgJBgH4Fn8bI+qxprPmipZ2XNEv/kqlMqzFfZZnEod/8nAQ15uNfLMGEtQX1cCQZJ0Efl3DbRRlSIm00Vf1cgRWHREezhWv9XDY2kmagVpRtG5zDMB0u3yD9eHmwNsLTzC/mLi7ZyWzn/BaU74klWJ7s2NVPHDTw3XORl2ZiFO0ylQAt5m7Tm58Yx4tl7y6OG380gZKEBCqItSsp9V6guhO9DdjmuDPwRH9WbVoZNkiISBNTyWfJKfxUwMzqciA/Mf4T16tpjZC8xkycTvL1vTzX1sW3ig2+XBAkI6P4R03YYCE+uW0jHE/x/bvWqEbLP39d3zgsLFVdLACpyN+uXIELyj0sOHF7a+rnF/wVqiTQ30VbiED4U="
    - secure: RExXZyxgB1BqdJ7ZdYx5hCyvzPA3W5eR/iLRCWusoHgxEwKKTDO6qcRSsdMfczDqrBtNj4uoIFG+4ZvEb7QpFeCoDA9TX9QlPvcEuzlPSBoSH1qKjA3Ca0V85KfzmdjGTcG62bUJLzGskqGPcHDaJtU7Me/nGr7mtsh6nzDxGNoi/hUgT+gcUofr5wBel+Vo759vZIUnC7mjSboafu7f587ru1Bamc2xT1vUckW2hPfBKoseiq4aoYIeu04onm6Nip4UQzPRCxuQiev3d57csF+UmO66pxUadMAad1SxEiDS424XVWJa0vAgJBgH4Fn8bI+qxprPmipZ2XNEv/kqlMqzFfZZnEod/8nAQ15uNfLMGEtQX1cCQZJ0Efl3DbRRlSIm00Vf1cgRWHREezhWv9XDY2kmagVpRtG5zDMB0u3yD9eHmwNsLTzC/mLi7ZyWzn/BaU74klWJ7s2NVPHDTw3XORl2ZiFO0ylQAt5m7Tm58Yx4tl7y6OG380gZKEBCqItSsp9V6guhO9DdjmuDPwRH9WbVoZNkiISBNTyWfJKfxUwMzqciA/Mf4T16tpjZC8xkycTvL1vTzX1sW3ig2+XBAkI6P4R03YYCE+uW0jHE/x/bvWqEbLP39d3zgsLFVdLACpyN+uXIELyj0sOHF7a+rnF/wVqiTQ30VbiED4U=
install:
- make dist
# for reporting coverage to codacy
- go get -u github.com/schrej/godacov

script:
- make test
- godacov -t "${CODACY_TOKEN}" -r ./coverage.out -c "${TRAVIS_COMMIT}"
deploy:
  provider: releases
  api_key:
    secure: ovt0GrPuwBP4OekGfSnxYYhKMI615xi/4Z0wLkPyawXMaA9zmhsfM1Yb880upueMjO4GyNJ9Je5f9UbaDNBISuWvgQg2unKdJRR2gj+Q/x/0KfmLa1EkIE1O8ovkOljGrOIBkrFAPXggJJtRWxo54JIbgeVZvprk/kglXZ0Qp39H0avS2/xJGzvNGgy8zX495PTTn1P+ZfWja+/WH6L7rTgWg8s5w3jRI5OcTX2eCHK8LkPFyyl5a6mhaSIAtJ/0e+aOUHuVD0axH/mR4cKG6+WZMHQGlTE+GmNr1bvXTBe85d4KS3JI4MyaTVd+TsrczT2AymtkqvadcUcms+PRA1kNM/P+4OWnxq6KShJXFi8+4yK74AEEwmGvOmuES28g2Z+hdTtr1tzyAo1O0p/Vmb6fVbBcHa1eFxt6RE9nO9PQ4GuVDXKomEmzUnCT+LJHBubLmCyE7aL7MO7UafWpGOYBHJuyxJvwsCYSWlbv6MHgdaaE0uKVGq/tJDNUMvMaKwyJ8nRhN2AIaRSQfGmhe2y3bdYuKmfRxvvOTGKOtuD7Omc/ybcql+3RG8JBJe3lkyGPQs3GFLYqQj/pR9TYTz/Af8SW7LQ6IsgPojezD5MYYCWhA/7Usp7NgviXen0Wqqre8itHpxKjePnoKqNR3Ug0pewhaq024fzaqlxMU3k=
  file: dist/*
  on:
    tags: true
  file_glob: true
  skip_cleanup: true
